#!/usr/bin/env node
// numbat-js build: scan vendored .nbt modules → generate src/vendored.js, then
// concatenate src/*.js into dist/numbat.js as a single ES module. Zero deps.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT       = dirname(fileURLToPath(import.meta.url));
const SRC        = join(ROOT, 'src');
const DIST       = join(ROOT, 'dist');
const VENDOR_DIR = join(ROOT, 'vendor', 'numbat', 'modules');

// Concat order: dependencies before dependents.
const SRC_FILES = [
  'dimensions.js',
  'quantity.js',
  'units.js',
  'format.js',
  'tokenize.js',
  'parse.js',
  // Typechecker (HM-style, dim-aware). Independent of load.js — operates
  // on AST + types only. Available to load.js if it chooses to opt-in.
  'typecheck/rat.js',
  'typecheck/types.js',
  'typecheck/env.js',
  'typecheck/constraints.js',
  'typecheck/check.js',
  'typecheck/subst.js',
  'typecheck/errors.js',
  'typecheck/dim-solve.js',
  'typecheck/unify.js',
  'typecheck/scheme.js',
  'typecheck/solve.js',
  'typecheck/integration.js',
  'load.js',
  'vendored.js',   // generated; safe to concat (only declares VENDORED_MODULES)
  'prelude.js',
  'api.js',
];

const PUBLIC_API = [
  'Numbat', 'Quantity', 'UnitRegistry', 'DimRegistry',
  // Dimension primitives — useful for hosts that want to manipulate dim vectors
  // directly without going through Quantity.
  'dimEq', 'dimMul', 'dimDiv', 'dimPow', 'dimInv', 'dimEmpty', 'dimFormat',
  // Number formatter — exposed so hosts can format raw numbers consistently.
  'formatNumber',
  // Parser/loader pieces (v0.2) — useful for hosts that want to embed Numbat
  // source loading without going through the Numbat class.
  'tokenize', 'parse', 'loadSource', 'loadModule', 'makeEnv',
  'evalDimExpr', 'evalValueExpr',
  // String-interpolation hook: hosts can supply a Quantity → {num, unit}
  // formatter so `"speed: {v}"` renders as "speed: 60 mph" instead of
  // "speed: <canonical-value> [?]". setPrintSink does the same for
  // `print` — useful for tests that capture output.
  'setQuantityFormatter', 'setPrintSink', 'setPlotSink',
  // formatParts is exposed so the unit-picker logic in ep can be
  // reused inside the interpolation hook.
  'formatParts',
  // Typechecker entry points — hosts (ep, future AIR integration) call
  // these to typecheck programs before/alongside evaluation.
  'typecheckStatement', 'typecheckModule', 'buildTypeEnv',
  // CSV → Dataset parsing (datasets Phase 1). detectCsvConfig sniffs a
  // best-guess parseConfig; parseCsv turns text + config into a Dataset.
  'parseCsv', 'detectCsvConfig',
  // Bundled vendored .nbt modules (v0.2) — Numbat.loadVendoredPrelude uses this.
  'VENDORED_MODULES',
];

function topLevelNames(strippedSrc) {
  const names = new Set();
  const re = /^(?:async\s+)?(?:const|let|var|function|class)\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/gm;
  let m;
  while ((m = re.exec(strippedSrc)) !== null) names.add(m[1]);
  return names;
}

function stripModule(src, file) {
  if (/^\s*import\s+\{[^}]*$/m.test(src)) {
    throw new Error(`${file}: multi-line imports are not allowed`);
  }
  if (/^\s*export\s+default\b/m.test(src)) {
    throw new Error(`${file}: \`export default\` is not allowed; use named exports`);
  }
  let out = src.replace(/^\s*import\s[^\n]*\n?/gm, '');
  out = out.replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$\n?/gm, '');
  out = out.replace(/^(\s*)export\s+/gm, '$1');
  return out;
}

// Walk vendor/numbat/modules/, return [{path: 'core::dimensions', source: '...'}, ...].
// The directory tree maps to module paths via '::' (so units/si.nbt → 'units::si').
function walkVendorModules() {
  const results = [];
  function walk(dir, prefix) {
    let entries;
    try { entries = readdirSync(dir); } catch { return; }
    for (const entry of entries) {
      const full = join(dir, entry);
      const s = statSync(full);
      if (s.isDirectory()) {
        walk(full, prefix ? `${prefix}::${entry}` : entry);
      } else if (entry.endsWith('.nbt')) {
        const name = entry.slice(0, -4);
        const path = prefix ? `${prefix}::${name}` : name;
        results.push({ path, source: readFileSync(full, 'utf8') });
      }
    }
  }
  walk(VENDOR_DIR, '');
  results.sort((a, b) => a.path.localeCompare(b.path));
  return results;
}

// Generate src/vendored.js exporting a map of vendored module paths to source
// text. Each source is JSON.stringify'd onto a single line so the line-based
// import/export strip can't be confused by content.
function generateVendored() {
  const modules = walkVendorModules();
  const lines = [
    '// AUTO-GENERATED by ext/numbat/build.js — do not edit by hand.',
    '// Source: ext/numbat/vendor/numbat/modules/*.nbt',
    '// Regenerate by running `node ext/numbat/build.js`.',
    '',
    'export const VENDORED_MODULES = {',
  ];
  for (const { path, source } of modules) {
    lines.push(`  ${JSON.stringify(path)}: ${JSON.stringify(source)},`);
  }
  lines.push('};');
  lines.push('');
  const out = lines.join('\n');
  writeFileSync(join(SRC, 'vendored.js'), out);
  console.log(`generated ext/numbat/src/vendored.js (${out.length.toLocaleString()} bytes, ${modules.length} modules)`);
}

function build() {
  generateVendored();

  const stripped = SRC_FILES.map(file => {
    const raw = readFileSync(join(SRC, file), 'utf8');
    return { name: file, src: stripModule(raw, file) };
  });

  // Cross-file top-level name collision check (flat scope after concat).
  const declOwner = new Map();
  const collisions = [];
  for (const { name, src } of stripped) {
    for (const decl of topLevelNames(src)) {
      const prior = declOwner.get(decl);
      if (prior) collisions.push({ name: decl, files: [prior, name] });
      else declOwner.set(decl, name);
    }
  }
  if (collisions.length) {
    const msg = collisions.map(c => `  ${c.name}: declared in both ${c.files[0]} and ${c.files[1]}`).join('\n');
    throw new Error(`top-level name collisions (flat-scope after build):\n${msg}`);
  }

  // Sanity: all PUBLIC_API names must actually be declared somewhere.
  for (const name of PUBLIC_API) {
    if (!declOwner.has(name)) {
      throw new Error(`PUBLIC_API references '${name}' but no source file declares it`);
    }
  }

  const parts = stripped.map(({ name, src }) => {
    const sep = `// ─── ${name} ` + '─'.repeat(Math.max(0, 50 - name.length)) + '\n';
    return sep + src.replace(/\s+$/, '');
  });

  const header =
    '// numbat-js v0.1 — built artifact, do not edit by hand.\n' +
    '// Source: ext/numbat/src/. Rebuild with `node ext/numbat/build.js`.\n\n';
  const exportLine = `\nexport { ${PUBLIC_API.join(', ')} };\n`;

  mkdirSync(DIST, { recursive: true });
  const out = header + parts.join('\n\n') + exportLine;
  writeFileSync(join(DIST, 'numbat.js'), out);
  console.log(`built ext/numbat/dist/numbat.js (${out.length.toLocaleString()} bytes, ${SRC_FILES.length} modules)`);
}

build();
